[project]
name = "langgraph-course"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Amrio", email = "emarco177@gmail.com" },
]
dependencies = [
    "langchain",
    "langgraph",
    "langchain-google_genai",
    "langchain-openai",
    "python-dotenv",
    "black",
    "isort",
    "langchain-tavily",
]

[tool.hatch.build.targets.wheel]
packages = ["src/langgraph_course"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"